transformed to web page
mate-academy/layout_human-rights pull request #100
Opened 2019-05-27 01:55 UTC by Hlybchenko

2019-05-27 16:52 UTC, ost-ptk requested changes

2019-05-27 16:52 UTC, gestap commented on src/style.css
> +  margin-bottom: 1em;
Try to write margin in one line.
It's better to read and debug.

2019-05-27 16:52 UTC, gestap commented on src/style.css
> +  margin-top: 0;
!

2019-05-27 16:52 UTC, gestap commented on src/style.css
> +  margin-bottom: 0;
!

2019-05-27 16:52 UTC, gestap commented on src/style.css
> +  font-size: 15px;
no need to write this.
`a` an inherit `font-size` from `h2`.

2019-05-28 05:16 UTC, mgrinko approved these changes
👍

2026-03-06 11:29 UTC, closed without merging