Declaration Webpage
mate-academy/layout_human-rights pull request #140
Opened 2019-07-22 12:57 UTC by amserhii11

Write Webpage of Declaration of Human Rights

2019-07-23 14:30 UTC, gestap commented on src/index.html
> +          <p> <h1> Universal Declaration of Human Rights </h1>
do not wrap `h1`, `h2` and other elements in `p`

2019-07-23 14:30 UTC, gestap commented on src/index.html
> +          <p> <h1> Universal Declaration of Human Rights </h1>
use 2 whitespaces instead of 4

2019-07-23 14:30 UTC, gestap commented on src/index.html
> +</html>
the document must end with one empty line
```suggestion
</html>

```

2019-07-23 14:30 UTC, gestap commented on src/style.css
> +h1 {
better to create class and style it

2019-07-23 14:30 UTC, gestap commented on src/style.css
> +  margin-bottom: 0;
try to write margin in one line

2019-07-24 14:41 UTC, YuriiHoliuk requested changes
Ostap comment not fixed

2019-07-25 10:26 UTC, gestap commented on src/index.html
> +    <p class=preamble> Whereas recognition of the inherent dignity and of the equal and inalienable
```suggestion
    <p class=preamble> 
      Whereas recognition of the inherent dignity and of the equal and inalienable
```

2019-07-25 10:26 UTC, gestap commented on src/index.html
> +            themselves and among the peoples of territories under their jurisdiction. </p>
```suggestion
            themselves and among the peoples of territories under their jurisdiction.
     </p>
```

2019-07-25 10:26 UTC, gestap commented on src/style.css
> +  margin-bottom: 1em;
use shorthand

2019-07-25 10:26 UTC, gestap commented on src/style.css
> +  font-weight: bold;
`h2` bold by default

2019-07-25 10:26 UTC, gestap commented on src/index.html
> +      <p>All human beings are born free and equal in dignity and rights. They are
```suggestion
      <p>
        All human beings are born free and equal in dignity and rights. They are
```

2019-07-25 10:26 UTC, gestap commented on src/index.html
> +            spirit of brotherhood.</p>
```suggestion
            spirit of brotherhood.
      </p> 
```

2025-09-02 14:44 UTC, closed without merging