task 3 'Human rights' - Done!
mate-academy/layout_human-rights pull request #477
Opened 2020-08-25 13:29 UTC by Atteroot

- [DEMO LINK](https://Atteroot.github.io/layout_human-rights/) <br>
- [TEST REPORT LINK](https://Atteroot.github.io/layout_human-rights/report/html_report/)

2020-08-25 16:47 UTC, solaryasha requested changes

2020-08-25 16:47 UTC, solaryasha commented on src/style.css
> +h1 {
Давай ще додамо класи для h1,h2,p,a і стилізуватимо класи. Це крута практика!

2020-08-26 06:56 UTC, Atteroot commented on src/style.css
> +h1 {
Fixed!

2020-08-26 07:06 UTC, solaryasha approved these changes
Nicely done ! 🚀

2021-03-23 18:59 UTC, closed without merging