The whole text added
mate-academy/layout_human-rights pull request #583
Opened 2021-01-12 13:07 UTC by Frant22

- [DEMO LINK](https://Frant22.github.io/layout_human-rights/)
- [TEST REPORT LINK](https://Frant22.github.io/layout_human-rights/report/html_report/)

2021-01-12 13:26 UTC, solaryasha requested changes

2021-01-12 13:26 UTC, solaryasha commented on src/style.css
> +h1 {
Давай додамо до заголовків і посилань класи і будемо їх стилізувати

2021-01-12 13:26 UTC, solaryasha commented on src/style.css
> +#link {
Краще застосуй клас

2021-01-12 14:09 UTC, Frant22 commented on src/style.css
> +h1 {
Исправл

2021-01-12 17:36 UTC, solaryasha requested changes

2021-01-12 17:36 UTC, solaryasha commented on src/style.css
> +.full {
для `body`клас можна і не задавати

2021-01-12 17:36 UTC, solaryasha commented on src/style.css
> +  font-weight: normal;
Ці два правила повторюють, запиши їх через кому

2021-01-12 17:36 UTC, solaryasha commented on src/style.css
> +.head1 {
```suggestion
.header {
```

2021-01-12 18:23 UTC, Frant22 commented on src/style.css
> +.full {
исправил

2021-01-12 18:23 UTC, Frant22 commented on src/style.css
> +  font-weight: normal;
когда пишу через запятую, не проходит тест, оставил как было

2021-01-12 18:23 UTC, Frant22 commented on src/style.css
> +.head1 {
исправил

2021-01-13 07:48 UTC, solaryasha approved these changes

2024-09-28 09:25 UTC, closed without merging