text was formatted
mate-academy/layout_human-rights pull request #604
Opened 2021-02-01 12:45 UTC by JohnCrownHC

- [DEMO LINK](https://JohnCrownHC.github.io/layout_human-rights/) <br>
- [TEST REPORT LINK](https://JohnCrownHC.github.io/layout_human-rights/report/html_report/)

2021-02-01 12:50 UTC, danheim commented
Do `npm run deploy`

2021-02-01 12:51 UTC, danheim requested changes

2021-02-01 12:51 UTC, danheim commented on src/style.css
> +  font-size: 13px;
font-family & font-size should be in `html` tag, not body

2021-02-01 13:26 UTC, JohnCrownHC commented
> Do `npm run deploy`, your links don't work

I fixed everything, should work now

2021-02-01 16:21 UTC, danheim requested changes

2021-02-01 16:21 UTC, danheim commented on src/index.html
> +    <h2><a href="https://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/eng.pdf">Articles 17 to 30</a></h2>
добавляй переносы, если слишком длинная строка
```suggestion
    <h2>
      <a href="https://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/eng.pdf">
        Articles 17 to 30
      </a>
    </h2>
```

2021-02-01 16:21 UTC, danheim commented on src/index.html
> +        </li>
переноси текст на новую строку
он должен быть между открывающим и закрывающим тегом

исправь везде этот момент
```suggestion
        <li>
          Men and women of full age, without any limitation due to race,
          nationality or religion, have the right to marry and to found a family.
          They are entitled to equal rights as to marriage, during marriage and at
          its dissolution.
        </li>
```

2021-02-02 09:19 UTC, danheim approved these changes

2024-04-18 12:41 UTC, closed without merging